# Generated by Django 5.0.4 on 2024-05-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addcategoryDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ac_description', models.CharField(blank=True, max_length=100, null=True)),
                ('ac_image', models.ImageField(blank=True, null=True, upload_to='ac_pic')),
            ],
        ),
    ]
