# Generated by Django 5.0.4 on 2024-05-11 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactDb',
        ),
    ]
