# Generated by Django 5.0.4 on 2024-05-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_contact_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_signIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_username', models.CharField(blank=True, max_length=50, null=True)),
                ('si_password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reg_signUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('su_username', models.CharField(blank=True, max_length=50, null=True)),
                ('su_password', models.CharField(blank=True, max_length=100, null=True)),
                ('su_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('su_pic', models.ImageField(blank=True, null=True, upload_to='signup_Profilepic')),
            ],
        ),
    ]
