# Generated by Django 5.0.4 on 2024-05-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_reg_signin_reg_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_signup',
            name='su_conformpassword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
