# Generated by Django 5.0.4 on 2024-05-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_reg_signup_su_conformpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_username', models.CharField(blank=True, max_length=50, null=True)),
                ('cart_productname', models.CharField(blank=True, max_length=50, null=True)),
                ('cart_quantity', models.IntegerField(blank=True, null=True)),
                ('cart_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Reg_signIn',
        ),
    ]
